// See https://aka.ms/new-console-template for more information
using GeneratorDemo.AutoGenerated;
using Microsoft.Extensions.DependencyInjection;

Console.WriteLine("Hello, World!");
ServiceCollection services = new();
services.AddAutoInjectServices();